In [1]:
%matplotlib inline

import logging

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn import datasets
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import numpy as np
import matplotlib.pyplot as plt

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(message)s')

In [2]:
digits = datasets.load_digits()

X_train, X_test, y_train, y_test = train_test_split(
    (digits.data[:-1] - digits.data[:-1].mean()) / 16.0,
    digits.target[:-1],
    test_size=0.2,
    random_state=42
)

In [3]:
from sklearn import svm

param_grid = {'C': np.linspace(5e-2, 1, 10),
              'gamma': np.linspace(1e-3, 1e-2, 10) }
clf = GridSearchCV(svm.SVC(kernel='rbf', class_weight='balanced'), param_grid)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print classification_report(y_test, y_pred, target_names=map(str, digits.target_names))
print clf.best_params_, len(clf.best_estimator_.support_)

KeyboardInterrupt: 

In [4]:
from sklearn.linear_model import SGDClassifier

param_grid = {'alpha': np.linspace(5e-1, 1, 10)}

clf = GridSearchCV(SGDClassifier(penalty='l2'), param_grid)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print classification_report(y_test, y_pred, target_names=map(str, digits.target_names))
print confusion_matrix(y_test, y_pred, labels=range(digits.target_names.shape[0]))
print clf.best_params_

             precision    recall  f1-score   support

          0       0.87      1.00      0.93        34
          1       0.85      0.85      0.85        26
          2       0.94      1.00      0.97        34
          3       0.93      0.90      0.92        31
          4       0.98      0.96      0.97        46
          5       0.95      0.98      0.96        42
          6       1.00      0.97      0.98        31
          7       0.84      0.98      0.90        42
          8       1.00      0.85      0.92        33
          9       0.88      0.73      0.80        41

avg / total       0.93      0.92      0.92       360

[[34  0  0  0  0  0  0  0  0  0]
 [ 0 22  2  1  0  0  0  0  0  1]
 [ 0  0 34  0  0  0  0  0  0  0]
 [ 0  0  0 28  0  1  0  2  0  0]
 [ 0  0  0  0 44  0  0  1  0  1]
 [ 0  0  0  0  0 41  0  0  0  1]
 [ 1  0  0  0  0  0 30  0  0  0]
 [ 0  0  0  0  0  1  0 41  0  0]
 [ 0  3  0  0  0  0  0  1 28  1]
 [ 4  1  0  1  1  0  0  4  0 30]]
{'alpha': 0.72222222222222221}

In [19]:
from sklearn.neural_network import MLPClassifier

param_grid = {'alpha': np.linspace(5e-5, 5e-4, 10)}

clf = GridSearchCV(MLPClassifier(solver='lbfgs', hidden_layer_sizes=(64, 256, 10)), param_grid)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print classification_report(y_test, y_pred, target_names=map(str, digits.target_names))
print confusion_matrix(y_test, y_pred, labels=range(digits.target_names.shape[0]))

             precision    recall  f1-score   support

          0       0.94      0.94      0.94        67
          1       0.97      0.97      0.97        71
          2       0.97      0.97      0.97        64
          3       0.91      0.97      0.94        72
          4       0.94      0.96      0.95        77
          5       0.96      0.95      0.95        76
          6       0.94      0.94      0.94        72
          7       0.97      0.94      0.95        78
          8       0.94      0.92      0.93        65
          9       0.95      0.92      0.93        77

avg / total       0.95      0.95      0.95       719

[[63  0  0  0  2  1  1  0  0  0]
 [ 0 69  0  0  0  0  0  0  2  0]
 [ 0  0 62  2  0  0  0  0  0  0]
 [ 0  0  0 70  0  1  0  0  1  0]
 [ 0  0  0  0 74  0  3  0  0  0]
 [ 0  1  0  0  0 72  0  1  0  2]
 [ 4  0  0  0  0  0 68  0  0  0]
 [ 0  0  1  0  2  0  0 73  0  2]
 [ 0  1  1  2  1  0  0  0 60  0]
 [ 0  0  0  3  0  1  0  1  1 71]]


In [46]:
from sklearn.neighbors import KNeighborsClassifier

param_grid = {'n_neighbors': range(5, 15)}

clf = GridSearchCV(KNeighborsClassifier(), param_grid)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print classification_report(y_test, y_pred, target_names=map(str, digits.target_names))
print confusion_matrix(y_test, y_pred, labels=range(digits.target_names.shape[0]))
print clf.best_params_

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        67
          1       0.96      1.00      0.98        71
          2       1.00      1.00      1.00        64
          3       0.99      0.99      0.99        72
          4       0.99      0.99      0.99        77
          5       1.00      1.00      1.00        76
          6       1.00      1.00      1.00        72
          7       0.97      1.00      0.99        78
          8       1.00      0.94      0.97        65
          9       0.99      0.97      0.98        77

avg / total       0.99      0.99      0.99       719

[[67  0  0  0  0  0  0  0  0  0]
 [ 0 71  0  0  0  0  0  0  0  0]
 [ 0  0 64  0  0  0  0  0  0  0]
 [ 0  0  0 71  0  0  0  1  0  0]
 [ 0  0  0  0 76  0  0  1  0  0]
 [ 0  0  0  0  0 76  0  0  0  0]
 [ 0  0  0  0  0  0 72  0  0  0]
 [ 0  0  0  0  0  0  0 78  0  0]
 [ 0  3  0  0  0  0  0  0 61  1]
 [ 0  0  0  1  1  0  0  0  0 75]]
{'n_neighbors': 7}


In [48]:
from sklearn.ensemble import RandomForestClassifier


clf = RandomForestClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print classification_report(y_test, y_pred, target_names=map(str, digits.target_names))
print confusion_matrix(y_test, y_pred, labels=range(digits.target_names.shape[0]))


             precision    recall  f1-score   support

          0       0.97      1.00      0.99        67
          1       0.92      0.97      0.95        71
          2       0.97      0.95      0.96        64
          3       0.96      0.94      0.95        72
          4       0.96      0.97      0.97        77
          5       0.97      0.92      0.95        76
          6       0.99      0.97      0.98        72
          7       0.94      0.97      0.96        78
          8       0.92      0.94      0.93        65
          9       0.95      0.90      0.92        77

avg / total       0.95      0.95      0.95       719

[[67  0  0  0  0  0  0  0  0  0]
 [ 0 69  1  0  0  0  0  0  1  0]
 [ 0  2 61  0  0  0  0  1  0  0]
 [ 0  1  0 68  0  0  1  1  1  0]
 [ 0  0  0  0 75  0  0  1  0  1]
 [ 0  1  0  1  2 70  0  0  0  2]
 [ 1  0  0  0  0  1 70  0  0  0]
 [ 0  0  0  0  0  0  0 76  1  1]
 [ 1  2  0  0  1  0  0  0 61  0]
 [ 0  0  1  2  0  1  0  2  2 69]]


In [75]:
classifiers = [
    { 'name': 'radial basis function',
     'clf': svm.SVC(kernel='rbf', class_weight='balanced'),
     'grid': {'C': np.linspace(2e1, 1e2, 10), 'gamma': np.linspace(1e-3, 1e-2, 10) }
    },
    { 'name': 'lin svm [l2 loss]',
     'clf': SGDClassifier(penalty='l2'),
     'grid': {'alpha': np.linspace(5e-1, 1, 10)}
    },
    { 'name': 'nn [64x256x10]',
     'clf': MLPClassifier(solver='lbfgs', hidden_layer_sizes=(64, 256, 10)),
     'grid': {'alpha': np.linspace(5e-5, 5e-4, 10)}
    },
    { 'name': 'random forest',
     'clf': RandomForestClassifier(),
     'grid': {}
    },
    { 'name': 'knn',
     'clf': KNeighborsClassifier(),
     'grid': {'n_neighbors': range(5, 15)}
    },
]

for c in classifiers:
    print "\n------------------------------------------------------------------"
    print "Classifier: %s" % c['name']
    
    clf = GridSearchCV(c['clf'], c['grid'])
    clf = clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    print "Best parameters: %s" % clf.best_params_
    print "Misclassified: (%d / %d)\n" % (sum(y_pred != y_test), len(y_test))
    print classification_report(y_test, y_pred, target_names=map(str, digits.target_names))



------------------------------------------------------------------
Classifier: radial basis function
Best parameters: {'C': 20.0, 'gamma': 0.01}
Misclassified: (6 / 360)

             precision    recall  f1-score   support

          0       0.97      1.00      0.99        34
          1       1.00      1.00      1.00        26
          2       1.00      1.00      1.00        34
          3       1.00      0.94      0.97        31
          4       1.00      1.00      1.00        46
          5       0.98      1.00      0.99        42
          6       1.00      0.97      0.98        31
          7       0.98      0.98      0.98        42
          8       0.94      1.00      0.97        33
          9       0.97      0.95      0.96        41

avg / total       0.98      0.98      0.98       360


------------------------------------------------------------------
Classifier: lin svm [l2 loss]
Best parameters: {'alpha': 0.94444444444444442}
Misclassified: (38 / 360)

             pre